// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using axxis.bacco.backend.infra.data.Contexts;

#nullable disable

namespace axxis.bacco.backend.infra.data.Migrations
{
    [DbContext(typeof(BaccoContext))]
    [Migration("20230811110123_EstruturaInicial")]
    partial class EstruturaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("Comandas_Id_seq");

            modelBuilder.HasSequence("FormasPagamento_Id_seq");

            modelBuilder.HasSequence("ItensVenda_Id_seq");

            modelBuilder.HasSequence("Pedidos_Id_seq");

            modelBuilder.HasSequence("Produtos_Id_seq");

            modelBuilder.HasSequence("Usuarios_Id_seq");

            modelBuilder.HasSequence("Vendas_Id_seq");

            modelBuilder.Entity("axxis.bacco.domain.Comandas.Comanda", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mesa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_COMANDAS");

                    b.HasIndex("DataAbertura")
                        .HasDatabaseName("IDX_COMANDA_DATAABERTURA");

                    b.HasIndex("Mesa")
                        .HasDatabaseName("IDX_COMANDA_MESA");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_COMANDA_STATUS");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comandas", (string)null);
                });

            modelBuilder.Entity("axxis.bacco.domain.FormasPagamento.FormaPagamento", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK_FORMASPAGAMENTO");

                    b.ToTable("FormasPagamento", (string)null);
                });

            modelBuilder.Entity("axxis.bacco.domain.ItensVenda.ItemVenda", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<double>("ValorTotalProduto")
                        .HasColumnType("double precision");

                    b.Property<double>("ValorVenda")
                        .HasColumnType("double precision");

                    b.Property<long>("VendaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VendaId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_ITENSVENDA");

                    b.HasIndex("DescricaoProduto")
                        .HasDatabaseName("IDX_ITENSVENDA_DESCRICAO");

                    b.HasIndex("VendaId");

                    b.HasIndex("VendaId1");

                    b.ToTable("ItensVenda", (string)null);
                });

            modelBuilder.Entity("axxis.bacco.domain.Pedidos.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ComandaId")
                        .HasColumnType("bigint");

                    b.Property<long>("ComandaId1")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("HoraPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<double>("ValorVenda")
                        .HasColumnType("double precision");

                    b.HasKey("Id")
                        .HasName("PK_PEDIDOS");

                    b.HasIndex("ComandaId");

                    b.HasIndex("ComandaId1");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("axxis.bacco.domain.Produtos.Produto", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Base64Image")
                        .IsRequired()
                        .HasMaxLength(614400)
                        .HasColumnType("character varying(614400)");

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("DescricaoLonga")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("TipoPedido")
                        .HasColumnType("integer");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("double precision");

                    b.HasKey("Id")
                        .HasName("PK_PRODUTOS");

                    b.HasIndex("DescricaoCurta")
                        .HasDatabaseName("IDX_PRODUTO_DESCRICAO");

                    b.HasIndex("DescricaoLonga")
                        .HasDatabaseName("IDX_PRODUTO_DESCL");

                    b.HasIndex("TipoPedido")
                        .HasDatabaseName("IDX_PRODUTO_TIPO");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("axxis.bacco.domain.Usuarios.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_USUARIOS");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("axxis.bacco.domain.Vendas.Venda", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ClienteCPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClienteTelefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FormaPagamentoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_VENDAS");

                    b.HasIndex("FormaPagamentoId");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("axxis.bacco.domain.Comandas.Comanda", b =>
                {
                    b.HasOne("axxis.bacco.domain.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_COMANDA_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("axxis.bacco.domain.ItensVenda.ItemVenda", b =>
                {
                    b.HasOne("axxis.bacco.domain.Vendas.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ITENSVENDA_VENDA");

                    b.HasOne("axxis.bacco.domain.Vendas.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("VendaId1");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("axxis.bacco.domain.Pedidos.Pedido", b =>
                {
                    b.HasOne("axxis.bacco.domain.Comandas.Comanda", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PEDIDO_COMANDA");

                    b.HasOne("axxis.bacco.domain.Comandas.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("axxis.bacco.domain.Produtos.Produto", b =>
                {
                    b.HasOne("axxis.bacco.domain.Pedidos.Pedido", null)
                        .WithOne("Produto")
                        .HasForeignKey("axxis.bacco.domain.Produtos.Produto", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PEDIDO_PRODUTO");
                });

            modelBuilder.Entity("axxis.bacco.domain.Vendas.Venda", b =>
                {
                    b.HasOne("axxis.bacco.domain.FormasPagamento.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_VENDA_PAGAMENTO");

                    b.Navigation("FormaPagamento");
                });

            modelBuilder.Entity("axxis.bacco.domain.Comandas.Comanda", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("axxis.bacco.domain.Pedidos.Pedido", b =>
                {
                    b.Navigation("Produto")
                        .IsRequired();
                });

            modelBuilder.Entity("axxis.bacco.domain.Vendas.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
